#!/usr/bin/env python
# coding: utf-8

# In[2]:


Sum = 0
l = [1,2,3,4,5,6,7,8,9,10]
for i in range(0,len(l)):
    Sum = Sum + l[i]
print(Sum)


# In[2]:


dic = {"1":50,"2":60,"3":70}
maxvalue = max(dic.items(),key = lambda x : x[1])
print(maxvalue[0])
print(maxvalue[1])


# In[6]:


def MaxLength(arr, n):
    count = 0 
    result = 0   
    for i in range(0, n):
        if (arr[i] == 0):
            count = 0
        else:
            count+= 1 
            result = max(result, count) 
    return result 
arr = [0,0,0,1,1,1,0,0,0,1,1,0,1,1,1,1,0,0,1,1] 
n = len(arr)   
print(getMaxLength(arr, n))


# In[ ]:




